Repository InftyAI/llmaz, pull requests merged in 2024-08, with the labels that each got.

#41 Add support for multithread when downloading weights
  .gitignore
  Dockerfile.loader
  Makefile
  README.md
  config/crd/bases/inference.llmaz.io_services.yaml
  llmaz/loader/model_hub/huggingface.py
  llmaz/main.py
  pkg/configs.go
  pkg/controller/inference/playground_controller.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#49 Update docs of examples
  README.md
  docs/examples/README.md
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#51 Add dependabot and issue & pr template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/CLEANUP.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/SUPPORT.md
  .github/ISSUE_TEMPLATE/new-release.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#55 Add golang ci test
  .github/dependabot.yaml
  .github/workflows/golang-workflow.yaml
  .golangci.yaml
  Makefile
  config/manager/kustomization.yaml
  hack/e2e-test.sh
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/util/util_test.go
  pkg/webhook/model_webhook.go
  pkg/webhook/playground_webhook.go
  test/e2e/suit_test.go
  test/integration/controller/inference/suit_test.go
  test/util/validation/validate_service.go
  test/util/wrapper/playground.go
  test/util/wrapper/service.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#57 Add baseline for tests
  .github/workflows/golang-workflow.yaml
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#45 Feat: support modelscope
  docs/examples/modelscope/model.yaml
  docs/examples/modelscope/playground.yaml
  llmaz/loader/model_hub/hub_factory.py
  llmaz/loader/model_hub/model_scope.py
  poetry.lock
  pyproject.toml
  test/integration/webhook/model_test.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#64 Add new rules to golangci
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/CLEANUP.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/SUPPORT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .golangci.yaml
  Makefile
  docs/.DS_Store
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#68 Support SGLang & modify model source API
  README.md
  api/core/v1alpha1/model_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/inference/v1alpha1/config_types.go
  client-go/applyconfiguration/core/v1alpha1/modelsource.go
  client-go/applyconfiguration/core/v1alpha1/modelspec.go
  client-go/applyconfiguration/utils.go
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/bases/llmaz.io_models.yaml
  config/samples/_v1alpha1_model.yaml
  docs/examples/README.md
  docs/examples/huggingface/sglang-playground.yaml
  docs/examples/modelscope/sglang-playground.yaml
  docs/examples/sglang/model.yaml
  docs/examples/sglang/playground.yaml
  docs/examples/vllm-huggingface/model.yaml
  docs/examples/vllm-huggingface/playground.yaml
  docs/examples/vllm-modelscope/model.yaml
  docs/examples/vllm-modelscope/playground.yaml
  docs/support-backends.md
  llmaz/loader/model_hub/huggingface.py
  llmaz/loader/model_hub/model_hub.py
  llmaz/loader/model_hub/model_scope.py
  llmaz/main.py
  pkg/configs.go
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/backend/sglang.go
  pkg/controller_helper/backend/vllm.go
  pkg/controller_helper/model_source/model_hub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/modelsource_test.go
  pkg/webhook/model_webhook.go
  poetry.lock
  test/integration/controller/inference/playground_test.go
  test/integration/webhook/playground_test.go
  test/util/validation/validate_playground.go
  test/util/validation/validate_service.go
  test/util/wrapper/model.go
  test/util/wrapper/playground.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#70 Fix: name must not contain dots
  README.md
  api/core/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/core/v1alpha1/modelhub.go
  client-go/applyconfiguration/core/v1alpha1/modelspec.go
  cmd/main.go
  config/webhook/manifests.yaml
  pkg/webhook/model_webhook.go
  pkg/webhook/playground_webhook.go
  pkg/webhook/service_webhook.go
  test/integration/webhook/model_test.go
  test/integration/webhook/playground_test.go
  test/integration/webhook/service_test.go
  test/integration/webhook/suit_test.go
  test/util/wrapper/service.go
Labels: bug, lgtm, approved, needs-priority, needs-triage

#71 Support Secrets to store HF_TOKEN
  Makefile
  README.md
  pkg/configs.go
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/model_source/model_hub.go
  pkg/webhook/service_webhook.go
  test/e2e/suit_test.go
  test/integration/controller/inference/suit_test.go
  test/integration/webhook/service_test.go
  test/util/validation/validate_service.go
  test/util/wrapper/service.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#75 Prepare for v0.0.2
  Makefile
  README.md
  docs/examples/vllm-huggingface/model.yaml
  docs/installation.md
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/backend/sglang.go
  pkg/controller_helper/backend/vllm.go
  pkg/controller_helper/model_source/modelhub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/modelsource_test.go
  test/e2e/suit_test.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#76 Change API Model to OpenModel
  README.md
  api/core/v1alpha1/model_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/core/v1alpha1/openmodel.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/typed/core/v1alpha1/core_client.go
  client-go/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  client-go/clientset/versioned/typed/core/v1alpha1/fake/fake_model.go
  client-go/clientset/versioned/typed/core/v1alpha1/fake/fake_openmodel.go
  client-go/clientset/versioned/typed/core/v1alpha1/generated_expansion.go
  client-go/clientset/versioned/typed/core/v1alpha1/model.go
  client-go/clientset/versioned/typed/core/v1alpha1/openmodel.go
  client-go/informers/externalversions/core/v1alpha1/interface.go
  client-go/informers/externalversions/core/v1alpha1/openmodel.go
  client-go/informers/externalversions/generic.go
  client-go/listers/core/v1alpha1/expansion_generated.go
  client-go/listers/core/v1alpha1/model.go
  client-go/listers/core/v1alpha1/openmodel.go
  cmd/main.go
  config/crd/bases/llmaz.io_openmodels.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in__openmodels.yaml
  config/crd/patches/webhook_in__openmodels.yaml
  config/rbac/_openmodel_editor_role.yaml
  config/rbac/_openmodel_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/_v1alpha1_openmodel.yaml
  config/webhook/manifests.yaml
  docs/examples/sglang/model.yaml
  docs/examples/vllm-huggingface/model.yaml
  docs/examples/vllm-modelscope/model.yaml
  docs/installation.md
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/controller/model_controller.go
  pkg/controller_helper/backend/backend.go
  pkg/controller_helper/backend/sglang.go
  pkg/controller_helper/backend/vllm.go
  pkg/controller_helper/model_source/modelhub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/modelsource_test.go
  pkg/webhook/openmodel_webhook.go
  test/e2e/playground_test.go
  test/e2e/suit_test.go
  test/integration/controller/inference/playground_test.go
  test/integration/controller/inference/service_test.go
  test/integration/webhook/model_test.go
  test/integration/webhook/suit_test.go
  test/util/mock.go
  test/util/validation/validate_playground.go
  test/util/validation/validate_service.go
  test/util/wrapper/model.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#79 dependency cleanup
  .github/dependabot.yaml
  .golangci.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#82 Mark project as alpha
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#83 Update code of conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTION.md
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#84 Update contributing.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#87 Support loading models from object store
  Dockerfile.loader
  Makefile
  README.md
  api/core/v1alpha1/model_types.go
  config/crd/bases/llmaz.io_openmodels.yaml
  docs/examples/README.md
  docs/examples/huggingface/model.yaml
  docs/examples/huggingface/playground.yaml
  docs/examples/modelscope/model.yaml
  docs/examples/modelscope/playground.yaml
  docs/examples/objstore-oss/model.yaml
  docs/examples/objstore-oss/playground.yaml
  llmaz/README.md
  llmaz/main.py
  llmaz/model_loader/__init__.py
  llmaz/model_loader/defaults.py
  llmaz/model_loader/model_hub/__init__.py
  llmaz/model_loader/model_hub/hub_factory.py
  llmaz/model_loader/model_hub/huggingface.py
  llmaz/model_loader/model_hub/model_hub.py
  llmaz/model_loader/model_hub/modelscope.py
  llmaz/model_loader/objstore/__init__.py
  llmaz/model_loader/objstore/objstore.py
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/backend/backend.go
  pkg/controller_helper/backend/sglang.go
  pkg/controller_helper/backend/vllm.go
  pkg/controller_helper/model_source/modelhub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/modelsource_test.go
  pkg/controller_helper/model_source/uri.go
  pkg/defaults.go
  pkg/util/uri.go
  pkg/util/uri_test.go
  pkg/util/util.go
  pkg/webhook/openmodel_webhook.go
  pkg/webhook/service_webhook.go
  poetry.lock
  pyproject.toml
  test/e2e/model_test.go
  test/integration/controller/inference/service_test.go
  test/integration/webhook/model_test.go
  test/integration/webhook/service_test.go
  test/util/mock.go
  test/util/validation/validate_playground.go
  test/util/validation/validate_service.go
  test/util/wrapper/model.go
  test/util/wrapper/service.go
Labels: feature, lgtm, approved, needs-priority, needs-triage, api-change

#89 Update Readme.md
  README.md
  docs/examples/README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#94 Support llama.cpp
  .gitignore
  .golangci.yaml
  Makefile
  README.md
  api/core/v1alpha1/model_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/inference/v1alpha1/config_types.go
  client-go/applyconfiguration/core/v1alpha1/modelsource.go
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/bases/llmaz.io_openmodels.yaml
  docs/examples/README.md
  docs/examples/llamacpp/README.md
  docs/examples/llamacpp/model.yaml
  docs/examples/llamacpp/playground.yaml
  docs/support-backends.md
  llmaz/README.md
  llmaz/main.py
  llmaz/model_loader/model_hub/huggingface.py
  llmaz/model_loader/model_hub/model_hub.py
  llmaz/model_loader/model_hub/modelscope.py
  llmaz/model_loader/objstore/objstore.py
  llmaz/tests/__init__.py
  llmaz/tests/test_hub_factory.py
  pkg/controller_helper/backend/backend.go
  pkg/controller_helper/backend/backend_test.go
  pkg/controller_helper/backend/llamacpp.go
  pkg/controller_helper/model_source/modelhub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/modelsource_test.go
  pkg/controller_helper/model_source/uri.go
  pkg/defaults.go
  pkg/webhook/openmodel_webhook.go
  poetry.lock
  pyproject.toml
  test/integration/controller/inference/playground_test.go
  test/integration/webhook/model_test.go
  test/integration/webhook/playground_test.go
  test/util/mock.go
  test/util/wrapper/model.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#95 add e2e tests with llama.cpp
  README.md
  docs/examples/README.md
  hack/e2e-test.sh
  hack/kind-config.yaml
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/controller/model_controller.go
  pkg/controller_helper/backend/llamacpp.go
  test/e2e/model_test.go
  test/e2e/playground_test.go
  test/util/consts.go
  test/util/validation/validate_model.go
  test/util/validation/validate_playground.go
  test/util/validation/validate_service.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#101 Prepare for v0.0.4
  docs/installation.md
  pkg/controller_helper/model_source/modelhub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/uri.go
  pkg/webhook/openmodel_webhook.go
  test/util/validation/validate_service.go
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#102 Stop sharing model weights across Pods in the same node
  README.md
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/bases/inference.llmaz.io_services.yaml
  pkg/controller_helper/model_source/modelhub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/uri.go
Labels: bug, lgtm, approved, needs-priority, needs-triage

#107 fix wrong field path in the openmodel webhook
  pkg/webhook/openmodel_webhook.go
Labels: bug, lgtm, approved, needs-priority, needs-triage

#111 Add model label to Playground
  hack/kind-config.yaml
  pkg/controller/inference/playground_controller.go
  pkg/webhook/playground_webhook.go
  test/e2e/playground_test.go
  test/integration/controller/inference/playground_test.go
  test/integration/webhook/playground_test.go
  test/util/mock.go
  test/util/validation/validate_playground.go
  test/util/wrapper/playground.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#109 Playground should be triggered to create Services and then Pods once the model is created
  pkg/controller/inference/playground_controller.go
  test/integration/controller/inference/playground_test.go
Labels: bug, lgtm, approved, needs-priority, needs-triage
