Repository InftyAI/llmaz, pull requests merged in 2024-09, with the labels that each got.

#118 [1/N] Add SpeculativeDecoding support
  README.md
  api/core/v1alpha1/model_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/inference/v1alpha1/config_types.go
  api/inference/v1alpha1/playground_types.go
  api/inference/v1alpha1/service_types.go
  api/inference/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/core/v1alpha1/multimodelsclaim.go
  client-go/applyconfiguration/inference/v1alpha1/playgroundspec.go
  client-go/applyconfiguration/inference/v1alpha1/servicespec.go
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/bases/inference.llmaz.io_services.yaml
  config/crd/bases/llmaz.io_openmodels.yaml
  config/manager/kustomization.yaml
  docs/assets/.DS_Store
  docs/examples/README.md
  docs/examples/llamacpp/model.yaml
  docs/examples/sglang/model.yaml
  docs/examples/speculative-decoding/vllm/model.yaml
  docs/examples/speculative-decoding/vllm/playground.yaml
  llmaz/README.md
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/backend/backend.go
  pkg/controller_helper/backend/llamacpp.go
  pkg/controller_helper/backend/sglang.go
  pkg/controller_helper/backend/vllm.go
  pkg/controller_helper/model_source/modelhub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/uri.go
  pkg/webhook/playground_webhook.go
  test/integration/controller/inference/playground_test.go
  test/integration/controller/inference/service_test.go
  test/integration/webhook/playground_test.go
  test/integration/webhook/service_test.go
  test/util/mock.go
  test/util/validation/validate_playground.go
  test/util/validation/validate_service.go
  test/util/wrapper/playground.go
  test/util/wrapper/service.go
Labels: feature, lgtm, approved, needs-priority, needs-triage, api-change

#120 Add new conditions to Playground
  config/manager/kustomization.yaml
  docs/examples/llamacpp/playground.yaml
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  test/e2e/suit_test.go
  test/integration/controller/inference/playground_test.go
  test/integration/controller/inference/service_test.go
  test/util/util.go
  test/util/validation/validate_playground.go
  test/util/validation/validate_service.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#121 [2/N] Support SpeculativeDecoding with llama.cpp
  docs/examples/README.md
  docs/examples/llamacpp/README.md
  docs/examples/llamacpp/playground.yaml
  docs/examples/speculative-decoding/llamacpp/model.yaml
  docs/examples/speculative-decoding/llamacpp/playground.yaml
  docs/examples/speculative-decoding/vllm/playground.yaml
  pkg/controller/inference/playground_controller.go
  pkg/controller_helper/backend/backend.go
  pkg/controller_helper/backend/llamacpp.go
  pkg/controller_helper/backend/llamacpp_test.go
  pkg/controller_helper/backend/sglang.go
  pkg/controller_helper/backend/sglang_test.go
  pkg/controller_helper/backend/vllm.go
  pkg/controller_helper/backend/vllm_test.go
  pkg/webhook/playground_webhook.go
  test/e2e/playground_test.go
  test/util/validation/validate_playground.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#125 Change ModelClaims API
  README.md
  api/core/v1alpha1/model_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/inference/v1alpha1/playground_types.go
  api/inference/v1alpha1/service_types.go
  api/inference/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/core/v1alpha1/modelclaims.go
  client-go/applyconfiguration/core/v1alpha1/modelrepresentative.go
  client-go/applyconfiguration/core/v1alpha1/multimodelsclaim.go
  client-go/applyconfiguration/inference/v1alpha1/playgroundspec.go
  client-go/applyconfiguration/inference/v1alpha1/servicespec.go
  client-go/applyconfiguration/utils.go
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/bases/inference.llmaz.io_services.yaml
  docs/examples/speculative-decoding/llamacpp/playground.yaml
  docs/examples/speculative-decoding/vllm/playground.yaml
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/backend/backend.go
  pkg/controller_helper/backend/llamacpp.go
  pkg/controller_helper/backend/llamacpp_test.go
  pkg/controller_helper/backend/sglang.go
  pkg/controller_helper/backend/sglang_test.go
  pkg/controller_helper/backend/vllm.go
  pkg/controller_helper/backend/vllm_test.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/webhook/playground_webhook.go
  pkg/webhook/service_webhook.go
  test/integration/controller/inference/playground_test.go
  test/integration/controller/inference/service_test.go
  test/integration/webhook/playground_test.go
  test/integration/webhook/service_test.go
  test/util/mock.go
  test/util/validation/validate_playground.go
  test/util/validation/validate_service.go
  test/util/wrapper/playground.go
  test/util/wrapper/service.go
Labels: feature, lgtm, approved, needs-priority, needs-triage, api-change

#127 Prepare for v0.0.6
  docs/installation.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#129 Add Architecture diagram
  README.md
  docs/assets/arch.png
  docs/develop.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#130 Update Architecture
  README.md
  docs/assets/arch.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#131 Update typo
  docs/assets/arch.png
Labels: documentation, lgtm, approved, do-not-merge/hold, needs-priority, needs-triage

#132 Update typo
  docs/assets/arch.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#136 Fix resource limits could be small than requests
  api/inference/v1alpha1/config_types.go
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  docs/assets/arch.png
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  test/integration/controller/inference/playground_test.go
Labels: bug, lgtm, approved, needs-priority, needs-triage

#138 [1/N] Add backendRuntime CRD
  PROJECT
  api/inference/v1alpha1/backendruntime_types.go
  api/inference/v1alpha1/config_types.go
  api/inference/v1alpha1/playground_types.go
  api/inference/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/inference/v1alpha1/backendruntimeconfig.go
  client-go/applyconfiguration/inference/v1alpha1/playgroundspec.go
  client-go/applyconfiguration/utils.go
  cmd/main.go
  config/crd/bases/inference.llmaz.io_backendruntimes.yaml
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/kustomization.yaml
  config/rbac/inference_backendruntime_editor_role.yaml
  config/rbac/inference_backendruntime_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/inference_v1alpha1_backendruntime.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  pkg/controller/inference/backendruntime_controller.go
  pkg/controller/inference/playground_controller.go
  pkg/webhook/backendruntime_webhook.go
  pkg/webhook/playground_webhook.go
  test/config/lws/leaderworkerset.yaml
  test/integration/controller/inference/suit_test.go
  test/integration/webhook/backendruntime_test.go
  test/integration/webhook/playground_test.go
  test/integration/webhook/suit_test.go
  test/util/mock.go
  test/util/validation/validate_playground.go
  test/util/wrapper/backend.go
  test/util/wrapper/playground.go
Labels: feature, lgtm, approved, needs-priority, needs-triage, api-change

#139 [2/N] Add backendRuntime implementation
  api/core/v1alpha1/model_types.go
  api/inference/v1alpha1/backendruntime_types.go
  api/inference/v1alpha1/config_types.go
  api/inference/v1alpha1/playground_types.go
  config/crd/bases/inference.llmaz.io_backendruntimes.yaml
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/bases/llmaz.io_openmodels.yaml
  config/rbac/role.yaml
  docs/assets/arch.png
  docs/examples/llamacpp/playground.yaml
  docs/examples/sglang/playground.yaml
  docs/examples/speculative-decoding/llamacpp/playground.yaml
  docs/examples/speculative-decoding/vllm/playground.yaml
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/backend/backend.go
  pkg/controller_helper/backend/backend_test.go
  pkg/controller_helper/backend/llamacpp.go
  pkg/controller_helper/backend/llamacpp_test.go
  pkg/controller_helper/backend/sglang.go
  pkg/controller_helper/backend/sglang_test.go
  pkg/controller_helper/backend/vllm.go
  pkg/controller_helper/backend/vllm_test.go
  pkg/controller_helper/backendruntime.go
  pkg/controller_helper/backendruntime_test.go
  pkg/controller_helper/helper.go
  pkg/util/util.go
  pkg/webhook/backendruntime_webhook.go
  test/config/backends/llamacpp.yaml
  test/config/backends/sglang.yaml
  test/config/backends/vllm.yaml
  test/e2e/playground_test.go
  test/e2e/suit_test.go
  test/integration/controller/inference/playground_test.go
  test/integration/controller/inference/suit_test.go
  test/integration/webhook/backendruntime_test.go
  test/integration/webhook/playground_test.go
  test/util/mock.go
  test/util/util.go
  test/util/validation/validate_playground.go
  test/util/wrapper/backend.go
  test/util/wrapper/playground.go
Labels: feature, lgtm, approved, needs-priority, needs-triage, api-change

#142 Add helm chart support
  Makefile
  chart/.helmignore
  chart/Chart.yaml
  chart/crds/backendruntime-crd.yaml
  chart/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  chart/crds/openmodel-crd.yaml
  chart/crds/playground-crd.yaml
  chart/crds/service-crd.yaml
  chart/templates/_helpers.tpl
  chart/templates/backends/llamacpp.yaml
  chart/templates/backends/sglang.yaml
  chart/templates/backends/vllm.yaml
  chart/templates/deployment.yaml
  chart/templates/leader-election-rbac.yaml
  chart/templates/manager-rbac.yaml
  chart/templates/metrics-reader-rbac.yaml
  chart/templates/metrics-service.yaml
  chart/templates/mutating-webhook-configuration.yaml
  chart/templates/proxy-rbac.yaml
  chart/templates/serviceaccount.yaml
  chart/templates/validating-webhook-configuration.yaml
  chart/templates/webhook-server-cert.yaml
  chart/templates/webhook-service.yaml
  chart/values.global.yaml
  chart/values.yaml
  config/manager/kustomization.yaml
  pkg/controller/inference/playground_controller.go
Labels: feature, lgtm, approved, do-not-merge/hold, needs-priority, needs-triage

#144 Add helm chart v0.0.1
  index.yaml
  llmaz-0.0.1.tgz
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#145 Support publish helm chart
  .github/workflows/publish-helm-chart.yml
  docs/assets/arch.png
Labels: do-not-merge/needs-kind, needs-priority, needs-triage

#146 Rename workflow name
  .github/workflows/publish-helm-chart.yaml
Labels: do-not-merge/needs-kind, needs-priority, needs-triage

#147 Fix filename error
  .github/workflows/publish-helm-chart.yaml
Labels: do-not-merge/needs-kind, needs-priority, needs-triage

#154 Update installation doc
  Makefile
  chart/templates/lws/leaderworkerset.yaml
  docs/installation.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#157 Refactor backendRuntime
  .github/workflows/publish-helm-chart.yaml
  Makefile
  api/core/v1alpha1/model_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/inference/v1alpha1/backendruntime_types.go
  chart/Chart.yaml
  chart/crds/backendruntime-crd.yaml
  chart/crds/playground-crd.yaml
  chart/crds/service-crd.yaml
  chart/templates/backends/llamacpp.yaml
  chart/templates/backends/sglang.yaml
  chart/templates/backends/vllm.yaml
  client-go/applyconfiguration/core/v1alpha1/modelclaims.go
  client-go/applyconfiguration/core/v1alpha1/modelrefer.go
  client-go/applyconfiguration/utils.go
  config/crd/bases/inference.llmaz.io_backendruntimes.yaml
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/bases/inference.llmaz.io_services.yaml
  docs/installation.md
  index.yaml
  pkg/controller/inference/playground_controller.go
  pkg/controller_helper/backendruntime.go
  pkg/controller_helper/helper.go
  pkg/webhook/backendruntime_webhook.go
  pkg/webhook/playground_webhook.go
  test/config/backends/llamacpp.yaml
  test/config/backends/sglang.yaml
  test/config/backends/vllm.yaml
  test/e2e/playground_test.go
  test/integration/webhook/backendruntime_test.go
  test/integration/webhook/playground_test.go
  test/util/mock.go
  test/util/wrapper/backend.go
  test/util/wrapper/playground.go
  test/util/wrapper/service.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#159 Add release checklist
  .github/ISSUE_TEMPLATE/new-release.md
  docs/installation.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#162 chore: bump LWS version to v0.4.0
  Makefile
  go.mod
  go.sum
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#164 chore: add unit test in util package
  pkg/util/uri.go
  pkg/util/uri_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#167 Update make generate
  client-go/applyconfiguration/core/v1alpha1/flavor.go
  client-go/applyconfiguration/core/v1alpha1/modelclaim.go
  client-go/applyconfiguration/core/v1alpha1/modelclaims.go
  client-go/applyconfiguration/core/v1alpha1/modelhub.go
  client-go/applyconfiguration/core/v1alpha1/modelrefer.go
  client-go/applyconfiguration/core/v1alpha1/modelsource.go
  client-go/applyconfiguration/core/v1alpha1/modelspec.go
  client-go/applyconfiguration/core/v1alpha1/modelstatus.go
  client-go/applyconfiguration/core/v1alpha1/openmodel.go
  client-go/applyconfiguration/inference/v1alpha1/backendruntimeconfig.go
  client-go/applyconfiguration/inference/v1alpha1/elasticconfig.go
  client-go/applyconfiguration/inference/v1alpha1/playground.go
  client-go/applyconfiguration/inference/v1alpha1/playgroundspec.go
  client-go/applyconfiguration/inference/v1alpha1/playgroundstatus.go
  client-go/applyconfiguration/inference/v1alpha1/resourcerequirements.go
  client-go/applyconfiguration/inference/v1alpha1/service.go
  client-go/applyconfiguration/inference/v1alpha1/servicespec.go
  client-go/applyconfiguration/inference/v1alpha1/servicestatus.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/typed/core/v1alpha1/fake/fake_openmodel.go
  client-go/clientset/versioned/typed/core/v1alpha1/openmodel.go
  client-go/clientset/versioned/typed/inference/v1alpha1/fake/fake_playground.go
  client-go/clientset/versioned/typed/inference/v1alpha1/fake/fake_service.go
  client-go/clientset/versioned/typed/inference/v1alpha1/playground.go
  client-go/clientset/versioned/typed/inference/v1alpha1/service.go
  client-go/informers/externalversions/factory.go
  client-go/listers/core/v1alpha1/openmodel.go
  client-go/listers/inference/v1alpha1/playground.go
  client-go/listers/inference/v1alpha1/service.go
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#169 update controller-gen
  chart/crds/backendruntime-crd.yaml
  chart/crds/openmodel-crd.yaml
  chart/crds/playground-crd.yaml
  chart/crds/service-crd.yaml
  chart/templates/manager-rbac.yaml
  chart/values.global.yaml
  config/crd/bases/inference.llmaz.io_backendruntimes.yaml
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  config/crd/bases/inference.llmaz.io_services.yaml
  config/crd/bases/llmaz.io_openmodels.yaml
  config/rbac/role.yaml
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#168 chore:update leader-elect chart config
  chart/values.global.yaml
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#170 feature(webhook): add BackendRuntimeConfig resources validation
  pkg/webhook/playground_webhook.go
  test/integration/webhook/playground_test.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#172 feat:support apply llmaz to any ns
  chart/values.global.yaml
  chart/values.yaml
  cmd/main.go
  config/default/manager_auth_proxy_patch.yaml
  pkg/cert/cert.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#173 Update installation doc
  Makefile
  chart/templates/backends/llamacpp.yaml
  chart/templates/backends/sglang.yaml
  chart/templates/backends/vllm.yaml
  chart/templates/lws/leaderworkerset.yaml
  chart/values.global.yaml
  docs/installation.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#174 fix:catch os error
  llmaz/model_loader/model_hub/util.py
Labels: bug, lgtm, approved, needs-priority, needs-triage

#175 fix:load models cost seconds
  llmaz/main.py
Labels: bug, lgtm, approved, needs-priority, needs-triage

#176 Update Revision default to main
  api/core/v1alpha1/model_types.go
  config/crd/bases/llmaz.io_openmodels.yaml
  pkg/controller_helper/model_source/modelsource_test.go
  test/e2e/playground_test.go
  test/integration/controller/inference/playground_test.go
  test/integration/webhook/model_test.go
  test/util/mock.go
  test/util/wrapper/model.go
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#177 Update arch
  docs/assets/arch.png
Labels: documentation, lgtm, approved, do-not-merge/needs-kind, needs-priority, needs-triage

#180 Remove namespace when getting OpenModel
  test/e2e/suit_test.go
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#179 Downsize model-loader image
  Dockerfile.loader
Labels: cleanup, lgtm, approved, needs-priority, needs-triage
