Repository InftyAI/llmaz, pull requests merged in 2024-10, with the labels that each got.

#181 Make field Command optional
  api/inference/v1alpha1/backendruntime_types.go
  config/crd/bases/inference.llmaz.io_backendruntimes.yaml
  docs/examples/sglang/playground.yaml
  docs/support-backends.md
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#183 Update helm files
  api/inference/v1alpha1/config_types.go
  chart/crds/backendruntime-crd.yaml
  chart/crds/openmodel-crd.yaml
  pkg/controller/inference/playground_controller.go
  test/integration/controller/inference/playground_test.go
  test/integration/webhook/playground_test.go
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#184 chore:update llama readme
  docs/examples/llamacpp/README.md
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#178 feat:update model loader
  .gitignore
  api/core/v1alpha1/model_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/core/v1alpha1/modelhub.go
  config/crd/bases/llmaz.io_openmodels.yaml
  llmaz/main.py
  llmaz/model_loader/constant.py
  llmaz/model_loader/defaults.py
  llmaz/model_loader/model_hub/hub_factory.py
  llmaz/model_loader/model_hub/huggingface.py
  llmaz/model_loader/model_hub/model_hub.py
  llmaz/model_loader/model_hub/modelscope.py
  llmaz/model_loader/model_hub/util.py
  llmaz/model_loader/objstore/objstore.py
  pkg/controller_helper/model_source/modelhub.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/modelsource_test.go
  pkg/webhook/openmodel_webhook.go
  test/e2e/playground_test.go
  test/integration/controller/inference/playground_test.go
  test/integration/webhook/model_test.go
  test/util/mock.go
  test/util/validation/validate_service.go
  test/util/wrapper/model.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#187 Release v0.0.8
  .github/ISSUE_TEMPLATE/new-release.md
  chart/Chart.yaml
  chart/crds/openmodel-crd.yaml
  chart/values.yaml
  config/crd/bases/llmaz.io_openmodels.yaml
  config/manager/kustomization.yaml
  docs/installation.md
  index.yaml
  pkg/defaults.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#188 Release v0.0.8
  .gitignore
  index.yaml
  llmaz-0.0.4.tgz
Labels: documentation, lgtm, approved
