Repository InftyAI/llmaz, pull requests merged in 2024-11, with the labels that each got.

#193 Support ollama
  README.md
  chart/templates/backends/ollama.yaml
  docs/examples/README.md
  docs/examples/ollama/model.yaml
  docs/examples/ollama/playground.yaml
  docs/support-backends.md
  pkg/controller_helper/backendruntime.go
  pkg/controller_helper/backendruntime_test.go
  pkg/controller_helper/model_source/modelsource.go
  pkg/controller_helper/model_source/uri.go
  pkg/webhook/openmodel_webhook.go
  test/config/backends/ollama.yaml
  test/e2e/playground_test.go
  test/integration/controller/inference/playground_test.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#200 Update README.md
  README.md
  docs/assets/arch.png
  docs/assets/overview.png
  pkg/controller_helper/backendruntime.go
  test/e2e/suit_test.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#201 update docs
  README.md
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#203 fix: helm INSTALLATION FAILED
  chart/templates/serviceaccount.yaml
Labels: bug, lgtm, approved, needs-priority, needs-triage

#209 Add preheat field
  .gitignore
  PROJECT
  README.md
  api/core/v1alpha1/model_types.go
  chart/crds/openmodel-crd.yaml
  chart/templates/manager-rbac.yaml
  cmd/main.go
  config/rbac/role.yaml
  docs/examples/llamacpp/README.md
  go.mod
  go.sum
  pkg/controller/core/model_controller.go
  pkg/controller/model_controller.go
  pkg/controller_helper/model_source/modelhub.go
  poetry.lock
  pyproject.toml
  test/integration/controller/inference/suit_test.go
  test/integration/webhook/backendruntime_test.go
Labels: feature, lgtm, approved, needs-priority, needs-triage
