Repository InftyAI/llmaz, pull requests merged in 2025-04, with the labels that each got.

#340 chore: remove todo
  pkg/controller/inference/playground_controller.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#344 chore: refactor handleUnexpectedCondition func
  pkg/controller/inference/playground_controller.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#341 fix(env): ensure BackendRuntimeConfig.Envs overrides base Envs
  pkg/controller/inference/playground_controller.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#346 Release v0.1.2
  index.yaml
  llmaz-0.0.8.tgz
Labels: cleanup, lgtm, approved

#357 Add open-webui as the default chatbot
  Makefile
  README.md
  chart/Chart.lock
  chart/Chart.yaml
  chart/templates/backends/llamacpp.yaml
  chart/templates/backends/ollama.yaml
  chart/templates/backends/sglang.yaml
  chart/templates/backends/tgi.yaml
  chart/templates/backends/vllm.yaml
  chart/templates/lws/leaderworkerset.yaml
  chart/templates/prometheus/prometheus.yaml
  chart/templates/prometheus/service-monitor.yaml
  chart/templates/prometheus/serviceaccount.yaml
  chart/values.global.yaml
  docs/examples/llamacpp/playground.yaml
  docs/open-webui.md
Labels: feature, lgtm, approved, needs-priority, needs-triage

#354 feature: install lws controller in llmaz-system namespace
  chart/templates/lws/leaderworkerset.yaml
  chart/values.global.yaml
Labels: feature, lgtm, approved, needs-priority, needs-triage

#358 feat: move lws controller replicas to global values
  chart/templates/lws/leaderworkerset.yaml
  chart/values.global.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#360 Add enovy ai gateway (helm dependencies + doc)
  chart/Chart.yaml
  chart/values.global.yaml
  docs/examples/envoy-ai-gateway/README.md
  docs/examples/envoy-ai-gateway/basic.yaml
  docs/examples/envoy-ai-gateway/envoy-ai-gateway.md
  docs/open-webui.md
Labels: feature, lgtm, approved, needs-priority, needs-triage

#365 Update readme.md with open-webui & envoy-ai-gateway usage
  README.md
  chart/Chart.lock
  chart/Chart.yaml
  chart/values.global.yaml
  docs/envoy-ai-gateway.md
  docs/examples/envoy-ai-gateway/README.md
  docs/examples/envoy-ai-gateway/basic.yaml
  docs/examples/envoy-ai-gateway/envoy-ai-gateway.md
  docs/installation.md
  docs/open-webui.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#366 Release v0.1.3
  chart/Chart.yaml
  chart/values.yaml
  config/manager/kustomization.yaml
  docs/installation.md
  index.yaml
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#369 update readme.md
  docs/envoy-ai-gateway.md
  docs/examples/README.md
  docs/open-webui.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#370 fix envoy ai gateway link
  docs/installation.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#372 reorganize yaml within one playground.yaml
  docs/examples/hostpath/model.yaml
  docs/examples/hostpath/playground.yaml
  docs/examples/hpa/model.yaml
  docs/examples/hpa/playground.yaml
  docs/examples/huggingface/model.yaml
  docs/examples/huggingface/playground.yaml
  docs/examples/llamacpp/model.yaml
  docs/examples/llamacpp/playground.yaml
  docs/examples/modelscope/model.yaml
  docs/examples/modelscope/playground.yaml
  docs/examples/multi-nodes/model.yaml
  docs/examples/multi-nodes/service.yaml
  docs/examples/objstore-oss/model.yaml
  docs/examples/objstore-oss/playground.yaml
  docs/examples/ollama/model.yaml
  docs/examples/ollama/playground.yaml
  docs/examples/sglang/model.yaml
  docs/examples/sglang/playground.yaml
  docs/examples/speculative-decoding/llamacpp/model.yaml
  docs/examples/speculative-decoding/llamacpp/playground.yaml
  docs/examples/speculative-decoding/vllm/model.yaml
  docs/examples/speculative-decoding/vllm/playground.yaml
  docs/examples/tgi/model.yaml
  docs/examples/tgi/playground.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#373 Add architecture image
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
  README.md
  docs/assets/arch.png
  docs/assets/infra.png
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#374 Update image
  docs/assets/arch.png
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#378 Add kep template
  docs/proposals/NNNN-template/README.md
  docs/proposals/NNNN-template/proposal.yaml
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#380 Clarify Kubernetes version requirement and fallback plan in Key Features
  README.md
  docs/installation.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#383 feat: update sglang version to v0.4.5 to fix /health_generate endpoint 404 error
  chart/values.global.yaml
  test/config/backends/sglang.yaml
Labels: bug, lgtm, approved, needs-priority, triage/accepted

#381 feat: add preStop hook for llamacpp and tgi in the BackendRuntime
  chart/templates/backends/llamacpp.yaml
  chart/templates/backends/tgi.yaml
  docs/examples/tgi/playground.yaml
  pkg/controller/inference/playground_controller.go
Labels: feature, lgtm, approved, needs-priority, triage/accepted
