Repository InftyAI/llmaz, pull requests merged in 2025-03, with the labels that each got.

#289 cleanup: upgrade vllm version to v0.7.3
  chart/templates/backends/vllm.yaml
  test/integration/webhook/backendruntime_test.go
  test/util/consts.go
  test/util/mock.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#291 Upgrade workflow to v0.1.5
  .github/workflows/golang-workflow.yaml
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#295 fix: fix some warnings when building images
  Dockerfile
  Dockerfile.loader
  Makefile
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#300 Add icon for project integration
  docs/assets/icon.svg
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#301 Update the workflow to v0.1.6
  .github/workflows/golang-workflow.yaml
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#302 Update the workflow to v0.1.7
  .github/workflows/golang-workflow.yaml
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#294 feat: spread container env to initContianers
  go.mod
  pkg/controller_helper/modelsource/modelhub.go
  pkg/controller_helper/modelsource/modelsource_test.go
  pkg/controller_helper/modelsource/uri.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#306 Update the workflow to v0.1.9
  .github/workflows/golang-workflow.yaml
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
Labels: cleanup, approved, needs-priority, needs-triage

#305 Increase the timeout to 10min
  test/util/consts.go
Labels: lgtm, do-not-merge/needs-kind, needs-priority, needs-triage

#308 Reduce the resource requirement for e2e tests
  config/manager/kustomization.yaml
  hack/kind-config.yaml
  test/config/backends/llamacpp.yaml
  test/e2e/playground_test.go
  test/util/consts.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#304 fix: omit validate model loader while protocol is ollama
  test/e2e/playground_test.go
  test/util/validation/validate_service.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#303 feature(BackendRuntime): support lifecycle hook fields for BackendRuntime
  api/inference/v1alpha1/backendruntime_types.go
  api/inference/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/inference/playground_controller.go
  pkg/controller_helper/backendruntime/backendruntime.go
  test/config/backends/fake_backend.yaml
  test/integration/controller/inference/playground_test.go
  test/util/validation/validate_playground.go
  test/util/wrapper/backend.go
Labels: feature, lgtm, approved, needs-priority, needs-triage, api-change

#311 [CI] Fix issue comment error
  .github/workflows/golang-workflow.yaml
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#312 add miss lifecycle crd yaml
  config/crd/bases/inference.llmaz.io_backendruntimes.yaml
  docs/reference/core.v1alpha1.md
  docs/reference/inference.v1alpha1.md
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#315 chore: fix BackendRuntime crds field Commands -> Command
  api/inference/v1alpha1/backendruntime_types.go
  api/inference/v1alpha1/zz_generated.deepcopy.go
  chart/crds/backendruntime-crd.yaml
  chart/crds/service-crd.yaml
  chart/templates/backends/llamacpp.yaml
  chart/templates/backends/ollama.yaml
  chart/templates/backends/sglang.yaml
  chart/templates/backends/vllm.yaml
  config/crd/bases/inference.llmaz.io_backendruntimes.yaml
  docs/reference/inference.v1alpha1.md
  pkg/controller/inference/playground_controller.go
  pkg/controller_helper/backendruntime/backendruntime.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/config/backends/fake_backend.yaml
  test/config/backends/llamacpp.yaml
  test/config/backends/ollama.yaml
  test/config/backends/sglang.yaml
  test/config/backends/vllm.yaml
  test/util/validation/validate_playground.go
  test/util/wrapper/backend.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage, api-change

#310 feat: add e2e test to verify service is avaliable
  go.mod
  go.sum
  test/e2e/playground_test.go
  test/util/validation/validate_service.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#319 feature: add in-tree vllm BackendRuntime for preStop Hook
  chart/templates/backends/vllm.yaml
Labels: feature, lgtm, approved, needs-priority, needs-triage

#321 cleanup: remove kube-rbac-proxy
  chart/templates/deployment.yaml
  chart/templates/metrics-reader-rbac.yaml
  chart/templates/metrics-service.yaml
  chart/templates/proxy-rbac.yaml
  chart/values.yaml
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_metrics_patch.yaml
  config/default/manager_metrics_service.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_client_binding.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  go.mod
  go.sum
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#322 use local GOPROXY
  Dockerfile
  Makefile
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#330 set GOPROXY only if it is not empty
  Makefile
  hack/boilerplate.go.txt
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#329 fix readme example of open model
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#331 feat: make elasticConfig.maxReplicas to a required parameter
  api/inference/v1alpha1/playground_types.go
  api/inference/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  pkg/controller/inference/playground_controller.go
  pkg/webhook/playground_webhook.go
  test/util/wrapper/playground.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#328 add image repo for lws and all backend runtime, like llama.cpp
  chart/templates/backends/llamacpp.yaml
  chart/templates/backends/ollama.yaml
  chart/templates/backends/sglang.yaml
  chart/templates/backends/tgi.yaml
  chart/templates/backends/vllm.yaml
  chart/templates/lws/leaderworkerset.yaml
  chart/values.global.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage
