Repository InftyAI/llmaz, pull requests merged in 2025-05, with the labels that each got.

#388 Initialize documentation site
  examples/README.md
  examples/envoy-ai-gateway/basic.yaml
  examples/hostpath/playground.yaml
  examples/hpa/README.md
  examples/hpa/playground.yaml
  examples/huggingface/playground.yaml
  examples/llamacpp/README.md
  examples/llamacpp/playground.yaml
  examples/modelscope/playground.yaml
  examples/multi-nodes/service.yaml
  examples/objstore-oss/playground.yaml
  examples/ollama/playground.yaml
  examples/sglang/playground.yaml
  examples/speculative-decoding/llamacpp/playground.yaml
  examples/speculative-decoding/vllm/playground.yaml
  examples/tgi/playground.yaml
  proposals/NNNN-template/README.md
  proposals/NNNN-template/proposal.yaml
  site/.gitignore
  site/assets/icons/logo.svg
  site/assets/scss/_styles_project.scss
  site/assets/scss/_variables_project.scss
  site/content/en/_index.md
  site/content/en/docs/_index.md
  site/content/en/docs/develop.md
  site/content/en/docs/installation.md
  site/content/en/docs/integrations/_index.md
  site/content/en/docs/integrations/envoy-ai-gateway.md
  site/content/en/docs/integrations/open-webui.md
  site/content/en/docs/integrations/prometheus-operator.md
  site/content/en/docs/integrations/support-backends.md
  site/content/en/docs/reference/_index.md
  site/content/en/docs/reference/core.v1alpha1.md
  site/content/en/docs/reference/inference.v1alpha1.md
  site/content/en/search.md
  site/go.mod
  site/go.sum
  site/hugo.toml
  site/layouts/404.html
  site/package.json
  site/static/favicons/android-144x144.png
  site/static/favicons/android-192x192.png
  site/static/favicons/android-36x36.png
  site/static/favicons/android-48x48.png
  site/static/favicons/android-72x72.png
  site/static/favicons/android-96x96.png
  site/static/favicons/android-chrome-192x192.png
  site/static/favicons/android-chrome-512x512.png
  site/static/favicons/android-chrome-maskable-192x192.png
  site/static/favicons/android-chrome-maskable-512x512.png
  site/static/favicons/apple-touch-icon-180x180.png
  site/static/favicons/favicon-16x16.png
  site/static/favicons/favicon-32x32.png
  site/static/favicons/favicon.ico
  site/static/images/arch.png
  site/static/images/infra.png
  site/static/images/logo.png
  site/static/images/prometheus.png
Labels: feature, lgtm, approved, needs-priority, needs-triage

#390 Fix diagram links
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#391 Update the helm install command
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  .github/workflows/deploy.yaml
  Makefile
  docs/examples/README.md
  docs/examples/envoy-ai-gateway/basic.yaml
  docs/examples/hostpath/playground.yaml
  docs/examples/hpa/README.md
  docs/examples/hpa/playground.yaml
  docs/examples/huggingface/playground.yaml
  docs/examples/llamacpp/README.md
  docs/examples/llamacpp/playground.yaml
  docs/examples/modelscope/playground.yaml
  docs/examples/multi-nodes/service.yaml
  docs/examples/objstore-oss/playground.yaml
  docs/examples/ollama/playground.yaml
  docs/examples/sglang/playground.yaml
  docs/examples/speculative-decoding/llamacpp/playground.yaml
  docs/examples/speculative-decoding/vllm/playground.yaml
  docs/examples/tgi/playground.yaml
  docs/proposals/NNNN-template/README.md
  docs/proposals/NNNN-template/proposal.yaml
  site/content/en/docs/installation.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#395 fix build error
  site/package.json
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#396 fix: doc links and makefile
  Makefile
  site/content/en/docs/installation.md
  site/content/en/docs/integrations/envoy-ai-gateway.md
  site/content/en/docs/integrations/prometheus-operator.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#397 fix README.md link
  README.md
  site/content/en/docs/installation.md
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#398 Update logo
  .github/workflows/deploy.yaml
  .github/workflows/golang-workflow.yaml
  .github/workflows/kube-workflow-init.yaml
  .github/workflows/kube-workflow.yaml
  site/assets/icons/logo-original.svg
  site/assets/icons/logo.svg
  site/assets/scss/_variables_project.scss
  site/static/images/logo-original.png
  site/static/images/logo.png
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#399 Polish website
  site/assets/scss/_variables_project.scss
  site/content/en/_index.md
  site/hugo.toml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#392 feat: add TensorRT-LLM as backend
  README.md
  chart/templates/backends/tensorrt-llm.yaml
  chart/values.global.yaml
  docs/examples/README.md
  docs/examples/tensorrt-llm/playground.yaml
  site/content/en/docs/integrations/support-backends.md
  test/config/backends/tensorrt-llm.yaml
Labels: feature, lgtm, approved, needs-priority, needs-triage

#403 Update envoy-ai-gateway docs and configs
  chart/templates/prometheus/serviceaccount.yaml
  chart/values.global.yaml
  docs/examples/envoy-ai-gateway/basic.yaml
  site/content/en/docs/integrations/envoy-ai-gateway.md
  site/content/en/docs/integrations/open-webui.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#402 feat: support speculative decoding for llamacpp
  api/inference/v1alpha1/config_types.go
  chart/templates/backends/llamacpp.yaml
  config/crd/bases/inference.llmaz.io_playgrounds.yaml
  docs/examples/README.md
  docs/examples/speculative-decoding/llamacpp/playground.yaml
  test/config/backends/llamacpp.yaml
  test/e2e/playground_test.go
Labels: feature, lgtm, approved, needs-priority, triage/accepted

#407 fix: remove trailing slashes from envoyproxy repository URLs in Chart.yaml
  chart/Chart.yaml
Labels: bug, lgtm, approved, needs-priority, needs-triage

#409 fix: fix wrong endpoint in envoy gateway test.
  site/content/en/docs/integrations/envoy-ai-gateway.md
Labels: cleanup, lgtm, approved, needs-priority, triage/accepted

#404 RFC: Gateway Metric Aggregator
  docs/proposals/376-metric-aggregagor/README.md
  docs/proposals/376-metric-aggregagor/flow.png
  docs/proposals/376-metric-aggregagor/proposal.yaml
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#410 Add homepage to website
  site/assets/icons/logo-original.svg
  site/assets/icons/logo-white.svg
  site/assets/icons/logo.svg
  site/content/en/_index.md
  site/content/en/docs/_index.md
  site/hugo.toml
  site/static/images/logo-original.png
  site/static/images/logo-white.png
  site/static/images/logo.png
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#415 cleanup: support custom logo path
  site/hugo.toml
  site/layouts/partials/navbar.html
Labels: feature, lgtm, approved, needs-priority, needs-triage

#416 Disable prometheus by default
  chart/values.global.yaml
  site/content/en/docs/installation.md
  site/content/en/docs/integrations/prometheus-operator.md
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#417 Update Website
  Makefile
  site/content/en/docs/getting-started/_index.md
  site/content/en/docs/getting-started/basic-usage.md
  site/content/en/docs/getting-started/installation.md
  site/content/en/docs/getting-started/prerequisites.md
  site/content/en/docs/integrations/envoy-ai-gateway.md
  site/content/en/docs/integrations/open-webui.md
  site/static/images/open-webui-setting.png
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#419 chore: add blog section and migrate
  site/archetypes/blog.md
  site/content/en/blog/_index.md
  site/content/en/blog/llmaz-intro.md
Labels: feature, lgtm, approved, needs-priority, needs-triage

#418 [Part-I] Metrics Aggregator implementation
  chart/templates/backends/llamacpp.yaml
  components/metrics-aggregator/cmd/main.go
  components/metrics-aggregator/config/manager/kustomization.yaml
  components/metrics-aggregator/go.mod
  components/metrics-aggregator/go.sum
  components/metrics-aggregator/pkg/aggregator/aggregator.go
  components/metrics-aggregator/pkg/aggregator/aggregator_test.go
  components/metrics-aggregator/pkg/backend/backend.go
  components/metrics-aggregator/pkg/backend/llamacpp.go
  components/metrics-aggregator/pkg/backend/vllm.go
  components/metrics-aggregator/pkg/controller/pod_controller.go
  components/metrics-aggregator/pkg/store/redis.go
  components/metrics-aggregator/pkg/store/store.go
  components/metrics-aggregator/pkg/util/consts.go
  components/metrics-aggregator/pkg/util/metricc_test.go
  components/metrics-aggregator/pkg/util/metrics.go
  components/metrics-aggregator/pkg/util/request.go
  site/content/en/docs/integrations/open-webui.md
  test/config/backends/llamacpp.yaml
Labels: feature, lgtm, approved, needs-priority, triage/accepted

#420 Update blog tags
  site/content/en/blog/llmaz-intro.md
Labels: documentation, lgtm, approved, needs-priority, triage/accepted

#427 Update README
  README.md
  api/core/v1alpha1/model_types.go
  site/static/images/arch.png
  site/static/images/infra.png
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#426 fix(dependencies): ai-gateway controller install error
  chart/Chart.lock
  chart/Chart.yaml
Labels: bug, lgtm, approved, needs-priority, needs-triage
