Repository InftyAI/llmaz, pull requests merged in 2025-06, with the labels that each got.

#432 Add ci test with helm chart
  .github/workflows/helm-chart-verify.yaml
  Makefile
  hack/test-deploy-with-helm.sh
  test/config/lws/leaderworkerset.yaml
Labels: feature, lgtm, approved, needs-priority, needs-triage

#428 fix: add ut for backend runtime.
  pkg/controller_helper/backendruntime/backendruntime_test.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#440 Add dispatcher & memoryStore & latencyAwarePlugin
  Makefile
  components/metrics-aggregator/pkg/store/redis.go
  components/metrics-aggregator/pkg/store/store.go
  components/router/.dockerignore
  components/router/.gitignore
  components/router/.golangci.yml
  components/router/Dockerfile
  components/router/Makefile
  components/router/PROJECT
  components/router/README.md
  components/router/cmd/main.go
  components/router/config/default/kustomization.yaml
  components/router/config/default/manager_auth_proxy_patch.yaml
  components/router/config/default/manager_config_patch.yaml
  components/router/config/manager/kustomization.yaml
  components/router/config/manager/manager.yaml
  components/router/config/prometheus/kustomization.yaml
  components/router/config/prometheus/monitor.yaml
  components/router/config/rbac/auth_proxy_client_clusterrole.yaml
  components/router/config/rbac/auth_proxy_role.yaml
  components/router/config/rbac/auth_proxy_role_binding.yaml
  components/router/config/rbac/auth_proxy_service.yaml
  components/router/config/rbac/kustomization.yaml
  components/router/config/rbac/leader_election_role.yaml
  components/router/config/rbac/leader_election_role_binding.yaml
  components/router/config/rbac/role.yaml
  components/router/config/rbac/role_binding.yaml
  components/router/config/rbac/service_account.yaml
  components/router/go.mod
  components/router/go.sum
  components/router/hack/boilerplate.go.txt
  components/router/pkg/backend/backend.go
  components/router/pkg/backend/llamacpp.go
  components/router/pkg/backend/vllm.go
  components/router/pkg/controller/pod_controller.go
  components/router/pkg/controller/pod_controller_test.go
  components/router/pkg/dispatcher/dispatcher.go
  components/router/pkg/dispatcher/framework/framework.go
  components/router/pkg/dispatcher/framework/registry.go
  components/router/pkg/dispatcher/framework/registry_test.go
  components/router/pkg/dispatcher/plugins/kvcache-aware/kvcache.go
  components/router/pkg/dispatcher/plugins/latency-aware/score.go
  components/router/pkg/metrics-aggregator/aggregator.go
  components/router/pkg/metrics-aggregator/aggregator_test.go
  components/router/pkg/store/mem.go
  components/router/pkg/store/mem_test.go
  components/router/pkg/store/metrics.go
  components/router/pkg/store/store.go
  components/router/pkg/util/consts.go
  components/router/pkg/util/metricc_test.go
  components/router/pkg/util/metrics.go
  components/router/pkg/util/request.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#441 fix logo url
  chart/README.md
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#442 Update slack link
  README.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#423 feat: support runai streamer for vllm
  api/inference/v1alpha1/playground_types.go
  docs/examples/README.md
  docs/examples/runai-streamer/playground-streaming-from-file-system.yaml
  docs/examples/runai-streamer/playground-streaming-from-s3.yaml
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/backendruntime/backendruntime.go
  pkg/controller_helper/helper.go
  pkg/controller_helper/modelsource/modelhub.go
  pkg/controller_helper/modelsource/modelsource.go
  pkg/controller_helper/modelsource/modelsource_test.go
  pkg/controller_helper/modelsource/uri.go
  pkg/util/uri.go
  pkg/webhook/openmodel_webhook.go
  test/e2e/playground_test.go
  test/util/validation/validate_service.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#447 Add inftyai-scheduler support and config updates
  chart/Chart.lock
  chart/Chart.yaml
  chart/values.global.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#448 Add Karpenter integration docs
  site/content/en/docs/features/_index.md
  site/content/en/docs/features/heterogeneous-cluster-support.md
  site/content/en/docs/getting-started/_index.md
  site/content/en/docs/getting-started/installation.md
  site/content/en/docs/integrations/_index.md
  site/content/en/docs/integrations/karpenter.md
  site/content/en/docs/integrations/open-webui.md
  site/content/en/docs/integrations/prometheus-operator.md
  site/content/en/docs/integrations/support-backends.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#449 Update documentation
  README.md
  site/content/en/_index.md
  site/content/en/docs/develop.md
  site/content/en/docs/features/broad-backends.md
  site/content/en/docs/features/distributed_inference.md
  site/content/en/docs/features/heterogeneous-cluster-support.md
  site/content/en/docs/reference/_index.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#450 Release v0.1.4
  chart/Chart.yaml
  chart/values.yaml
  config/manager/kustomization.yaml
  index.yaml
  site/content/en/docs/getting-started/installation.md
Labels: documentation, lgtm, approved, needs-priority, needs-triage

#438 feat: add ownedBy and createdAt for OpenModel
  api/core/v1alpha1/model_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/core/v1alpha1/modelspec.go
  config/crd/bases/llmaz.io_openmodels.yaml
  pkg/webhook/openmodel_webhook.go
  site/content/en/docs/reference/core.v1alpha1.md
  test/integration/webhook/model_test.go
  test/util/validation/validate_model.go
  test/util/wrapper/model.go
Labels: feature, lgtm, approved, needs-priority, needs-triage

#455 add miss integration test case for tensorrt-llm backend
  test/integration/controller/inference/playground_test.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#459 Update lws dependency to 0.6.2
  chart/Chart.lock
  chart/Chart.yaml
  config/crd/bases/inference.llmaz.io_services.yaml
  go.mod
  go.sum
  pkg/controller/inference/playground_controller.go
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/modelsource/modelhub.go
  pkg/controller_helper/modelsource/modelhub_test.go
  pkg/controller_helper/modelsource/modelsource.go
  pkg/controller_helper/modelsource/modelsource_test.go
  pkg/controller_helper/modelsource/uri.go
  test/config/lws/leaderworkerset.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#465 Polish the architecture of metrics aggregator
  components/router/pkg/store/mem.go
  components/router/pkg/store/store.go
  docs/proposals/376-metric-aggregagor/README.md
  docs/proposals/376-metric-aggregagor/flow.png
  docs/proposals/376-metric-aggregagor/proposal.yaml
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#467 add more integration test for model webhook(set custom createdAt)
  test/integration/webhook/model_test.go
  test/util/wrapper/model.go
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#471 Use slack as well
  README.md
Labels: cleanup, lgtm, approved, needs-priority, needs-triage

#443 feat: support configuring init container image
  config/default/configmap.yaml
  pkg/controller/inference/service_controller.go
  pkg/controller_helper/configmap.go
  pkg/controller_helper/configmap_test.go
  pkg/controller_helper/modelsource/modelhub.go
  pkg/controller_helper/modelsource/modelhub_test.go
  pkg/controller_helper/modelsource/modelsource.go
  pkg/controller_helper/modelsource/modelsource_test.go
  pkg/controller_helper/modelsource/uri.go
  pkg/defaults.go
  test/util/validation/validate_service.go
Labels: feature, lgtm, approved, needs-priority, needs-triage
